### PR TITLE
 http://drupal.org/node/1256722 : Awkward language around following

### PR DESCRIPTION
**Pull request by ezra-g**

### CODE REVIEW

**Comment by IceCreamYou** [comment]
I would put a hook_rules_defaults_alter() or something in commons_status_streams instead of editing Activity Log directly.

**Comment by ezra-g** [comment]
Is there a specific hook you suggest that we use? I'm not aware of one that's applicable here.
http://drupalcontrib.org/api/search/6/hook_rules

**Comment by ezra-g** [comment]
This now includes documentation in Patches.txt.

**Comment by mikestefanello** [comment]
Using Rules patch from http://drupal.org/node/978620 to provide hook_rules_defaults_alter(). Changes to the rule templates are then made in commons_status_streams.

**Pull request closed without merging**
